/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSeuProtocoloRouteImport } from './routes/_authenticated/seu-protocolo'
import { Route as AuthenticatedQuizFase1RouteImport } from './routes/_authenticated/quiz-fase-1'
import { Route as AuthenticatedProtocoloRouteImport } from './routes/_authenticated/protocolo'
import { Route as AuthenticatedPontosRouteImport } from './routes/_authenticated/pontos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedFlacidezRouteImport } from './routes/_authenticated/flacidez'
import { Route as AuthenticatedFase2RouteImport } from './routes/_authenticated/fase-2'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProtocoloIndexRouteImport } from './routes/_authenticated/protocolo.index'
import { Route as AuthenticatedAulasIndexRouteImport } from './routes/_authenticated/aulas.index'
import { Route as ApiPublicGrantAccessRouteImport } from './routes/api/public/grant-access'
import { Route as ApiPublicCheckAccessRouteImport } from './routes/api/public/check-access'
import { Route as AuthenticatedSugestoesChefeTipoRouteImport } from './routes/_authenticated/sugestoes-chefe.$tipo'
import { Route as AuthenticatedProtocoloFase2RouteImport } from './routes/_authenticated/protocolo.fase-2'
import { Route as AuthenticatedProtocoloFase1RouteImport } from './routes/_authenticated/protocolo.fase-1'
import { Route as AuthenticatedAulasLessonIdRouteImport } from './routes/_authenticated/aulas.$lessonId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksWhatsappCommandsRouteImport } from './routes/api/public/webhooks/whatsapp-commands'
import { Route as ApiPublicWebhooksPaytRouteImport } from './routes/api/public/webhooks/payt'
import { Route as AuthenticatedAulasModuloModuloIdRouteImport } from './routes/_authenticated/aulas.modulo.$moduloId'
import { Route as ApiPublicWebhooksPaytReprocessRouteImport } from './routes/api/public/webhooks/payt.reprocess'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeuProtocoloRoute =
  AuthenticatedSeuProtocoloRouteImport.update({
    id: '/seu-protocolo',
    path: '/seu-protocolo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizFase1Route = AuthenticatedQuizFase1RouteImport.update({
  id: '/quiz-fase-1',
  path: '/quiz-fase-1',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtocoloRoute = AuthenticatedProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPontosRoute = AuthenticatedPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlacidezRoute = AuthenticatedFlacidezRouteImport.update({
  id: '/flacidez',
  path: '/flacidez',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFase2Route = AuthenticatedFase2RouteImport.update({
  id: '/fase-2',
  path: '/fase-2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtocoloIndexRoute =
  AuthenticatedProtocoloIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProtocoloRoute,
  } as any)
const AuthenticatedAulasIndexRoute = AuthenticatedAulasIndexRouteImport.update({
  id: '/aulas/',
  path: '/aulas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicGrantAccessRoute = ApiPublicGrantAccessRouteImport.update({
  id: '/api/public/grant-access',
  path: '/api/public/grant-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckAccessRoute = ApiPublicCheckAccessRouteImport.update({
  id: '/api/public/check-access',
  path: '/api/public/check-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSugestoesChefeTipoRoute =
  AuthenticatedSugestoesChefeTipoRouteImport.update({
    id: '/sugestoes-chefe/$tipo',
    path: '/sugestoes-chefe/$tipo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProtocoloFase2Route =
  AuthenticatedProtocoloFase2RouteImport.update({
    id: '/fase-2',
    path: '/fase-2',
    getParentRoute: () => AuthenticatedProtocoloRoute,
  } as any)
const AuthenticatedProtocoloFase1Route =
  AuthenticatedProtocoloFase1RouteImport.update({
    id: '/fase-1',
    path: '/fase-1',
    getParentRoute: () => AuthenticatedProtocoloRoute,
  } as any)
const AuthenticatedAulasLessonIdRoute =
  AuthenticatedAulasLessonIdRouteImport.update({
    id: '/aulas/$lessonId',
    path: '/aulas/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappCommandsRoute =
  ApiPublicWebhooksWhatsappCommandsRouteImport.update({
    id: '/api/public/webhooks/whatsapp-commands',
    path: '/api/public/webhooks/whatsapp-commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaytRoute = ApiPublicWebhooksPaytRouteImport.update({
  id: '/api/public/webhooks/payt',
  path: '/api/public/webhooks/payt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAulasModuloModuloIdRoute =
  AuthenticatedAulasModuloModuloIdRouteImport.update({
    id: '/aulas/modulo/$moduloId',
    path: '/aulas/modulo/$moduloId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhooksPaytReprocessRoute =
  ApiPublicWebhooksPaytReprocessRouteImport.update({
    id: '/reprocess',
    path: '/reprocess',
    getParentRoute: () => ApiPublicWebhooksPaytRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/fase-2': typeof AuthenticatedFase2Route
  '/flacidez': typeof AuthenticatedFlacidezRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pontos': typeof AuthenticatedPontosRoute
  '/protocolo': typeof AuthenticatedProtocoloRouteWithChildren
  '/quiz-fase-1': typeof AuthenticatedQuizFase1Route
  '/seu-protocolo': typeof AuthenticatedSeuProtocoloRoute
  '/api/chat': typeof ApiChatRoute
  '/aulas/$lessonId': typeof AuthenticatedAulasLessonIdRoute
  '/protocolo/fase-1': typeof AuthenticatedProtocoloFase1Route
  '/protocolo/fase-2': typeof AuthenticatedProtocoloFase2Route
  '/sugestoes-chefe/$tipo': typeof AuthenticatedSugestoesChefeTipoRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/grant-access': typeof ApiPublicGrantAccessRoute
  '/aulas/': typeof AuthenticatedAulasIndexRoute
  '/protocolo/': typeof AuthenticatedProtocoloIndexRoute
  '/aulas/modulo/$moduloId': typeof AuthenticatedAulasModuloModuloIdRoute
  '/api/public/webhooks/payt': typeof ApiPublicWebhooksPaytRouteWithChildren
  '/api/public/webhooks/whatsapp-commands': typeof ApiPublicWebhooksWhatsappCommandsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/payt/reprocess': typeof ApiPublicWebhooksPaytReprocessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/fase-2': typeof AuthenticatedFase2Route
  '/flacidez': typeof AuthenticatedFlacidezRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pontos': typeof AuthenticatedPontosRoute
  '/quiz-fase-1': typeof AuthenticatedQuizFase1Route
  '/seu-protocolo': typeof AuthenticatedSeuProtocoloRoute
  '/api/chat': typeof ApiChatRoute
  '/aulas/$lessonId': typeof AuthenticatedAulasLessonIdRoute
  '/protocolo/fase-1': typeof AuthenticatedProtocoloFase1Route
  '/protocolo/fase-2': typeof AuthenticatedProtocoloFase2Route
  '/sugestoes-chefe/$tipo': typeof AuthenticatedSugestoesChefeTipoRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/grant-access': typeof ApiPublicGrantAccessRoute
  '/aulas': typeof AuthenticatedAulasIndexRoute
  '/protocolo': typeof AuthenticatedProtocoloIndexRoute
  '/aulas/modulo/$moduloId': typeof AuthenticatedAulasModuloModuloIdRoute
  '/api/public/webhooks/payt': typeof ApiPublicWebhooksPaytRouteWithChildren
  '/api/public/webhooks/whatsapp-commands': typeof ApiPublicWebhooksWhatsappCommandsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/payt/reprocess': typeof ApiPublicWebhooksPaytReprocessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/fase-2': typeof AuthenticatedFase2Route
  '/_authenticated/flacidez': typeof AuthenticatedFlacidezRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/pontos': typeof AuthenticatedPontosRoute
  '/_authenticated/protocolo': typeof AuthenticatedProtocoloRouteWithChildren
  '/_authenticated/quiz-fase-1': typeof AuthenticatedQuizFase1Route
  '/_authenticated/seu-protocolo': typeof AuthenticatedSeuProtocoloRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/aulas/$lessonId': typeof AuthenticatedAulasLessonIdRoute
  '/_authenticated/protocolo/fase-1': typeof AuthenticatedProtocoloFase1Route
  '/_authenticated/protocolo/fase-2': typeof AuthenticatedProtocoloFase2Route
  '/_authenticated/sugestoes-chefe/$tipo': typeof AuthenticatedSugestoesChefeTipoRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/grant-access': typeof ApiPublicGrantAccessRoute
  '/_authenticated/aulas/': typeof AuthenticatedAulasIndexRoute
  '/_authenticated/protocolo/': typeof AuthenticatedProtocoloIndexRoute
  '/_authenticated/aulas/modulo/$moduloId': typeof AuthenticatedAulasModuloModuloIdRoute
  '/api/public/webhooks/payt': typeof ApiPublicWebhooksPaytRouteWithChildren
  '/api/public/webhooks/whatsapp-commands': typeof ApiPublicWebhooksWhatsappCommandsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/payt/reprocess': typeof ApiPublicWebhooksPaytReprocessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/boas-vindas'
    | '/diagnostico'
    | '/fase-2'
    | '/flacidez'
    | '/hoje'
    | '/intake'
    | '/perfil'
    | '/pontos'
    | '/protocolo'
    | '/quiz-fase-1'
    | '/seu-protocolo'
    | '/api/chat'
    | '/aulas/$lessonId'
    | '/protocolo/fase-1'
    | '/protocolo/fase-2'
    | '/sugestoes-chefe/$tipo'
    | '/api/public/check-access'
    | '/api/public/grant-access'
    | '/aulas/'
    | '/protocolo/'
    | '/aulas/modulo/$moduloId'
    | '/api/public/webhooks/payt'
    | '/api/public/webhooks/whatsapp-commands'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/payt/reprocess'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/boas-vindas'
    | '/diagnostico'
    | '/fase-2'
    | '/flacidez'
    | '/hoje'
    | '/intake'
    | '/perfil'
    | '/pontos'
    | '/quiz-fase-1'
    | '/seu-protocolo'
    | '/api/chat'
    | '/aulas/$lessonId'
    | '/protocolo/fase-1'
    | '/protocolo/fase-2'
    | '/sugestoes-chefe/$tipo'
    | '/api/public/check-access'
    | '/api/public/grant-access'
    | '/aulas'
    | '/protocolo'
    | '/aulas/modulo/$moduloId'
    | '/api/public/webhooks/payt'
    | '/api/public/webhooks/whatsapp-commands'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/payt/reprocess'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/diagnostico'
    | '/_authenticated/fase-2'
    | '/_authenticated/flacidez'
    | '/_authenticated/hoje'
    | '/_authenticated/intake'
    | '/_authenticated/perfil'
    | '/_authenticated/pontos'
    | '/_authenticated/protocolo'
    | '/_authenticated/quiz-fase-1'
    | '/_authenticated/seu-protocolo'
    | '/api/chat'
    | '/_authenticated/aulas/$lessonId'
    | '/_authenticated/protocolo/fase-1'
    | '/_authenticated/protocolo/fase-2'
    | '/_authenticated/sugestoes-chefe/$tipo'
    | '/api/public/check-access'
    | '/api/public/grant-access'
    | '/_authenticated/aulas/'
    | '/_authenticated/protocolo/'
    | '/_authenticated/aulas/modulo/$moduloId'
    | '/api/public/webhooks/payt'
    | '/api/public/webhooks/whatsapp-commands'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/payt/reprocess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicCheckAccessRoute: typeof ApiPublicCheckAccessRoute
  ApiPublicGrantAccessRoute: typeof ApiPublicGrantAccessRoute
  ApiPublicWebhooksPaytRoute: typeof ApiPublicWebhooksPaytRouteWithChildren
  ApiPublicWebhooksWhatsappCommandsRoute: typeof ApiPublicWebhooksWhatsappCommandsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seu-protocolo': {
      id: '/_authenticated/seu-protocolo'
      path: '/seu-protocolo'
      fullPath: '/seu-protocolo'
      preLoaderRoute: typeof AuthenticatedSeuProtocoloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz-fase-1': {
      id: '/_authenticated/quiz-fase-1'
      path: '/quiz-fase-1'
      fullPath: '/quiz-fase-1'
      preLoaderRoute: typeof AuthenticatedQuizFase1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolo': {
      id: '/_authenticated/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof AuthenticatedProtocoloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pontos': {
      id: '/_authenticated/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof AuthenticatedPontosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flacidez': {
      id: '/_authenticated/flacidez'
      path: '/flacidez'
      fullPath: '/flacidez'
      preLoaderRoute: typeof AuthenticatedFlacidezRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fase-2': {
      id: '/_authenticated/fase-2'
      path: '/fase-2'
      fullPath: '/fase-2'
      preLoaderRoute: typeof AuthenticatedFase2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolo/': {
      id: '/_authenticated/protocolo/'
      path: '/'
      fullPath: '/protocolo/'
      preLoaderRoute: typeof AuthenticatedProtocoloIndexRouteImport
      parentRoute: typeof AuthenticatedProtocoloRoute
    }
    '/_authenticated/aulas/': {
      id: '/_authenticated/aulas/'
      path: '/aulas'
      fullPath: '/aulas/'
      preLoaderRoute: typeof AuthenticatedAulasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/grant-access': {
      id: '/api/public/grant-access'
      path: '/api/public/grant-access'
      fullPath: '/api/public/grant-access'
      preLoaderRoute: typeof ApiPublicGrantAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-access': {
      id: '/api/public/check-access'
      path: '/api/public/check-access'
      fullPath: '/api/public/check-access'
      preLoaderRoute: typeof ApiPublicCheckAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sugestoes-chefe/$tipo': {
      id: '/_authenticated/sugestoes-chefe/$tipo'
      path: '/sugestoes-chefe/$tipo'
      fullPath: '/sugestoes-chefe/$tipo'
      preLoaderRoute: typeof AuthenticatedSugestoesChefeTipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolo/fase-2': {
      id: '/_authenticated/protocolo/fase-2'
      path: '/fase-2'
      fullPath: '/protocolo/fase-2'
      preLoaderRoute: typeof AuthenticatedProtocoloFase2RouteImport
      parentRoute: typeof AuthenticatedProtocoloRoute
    }
    '/_authenticated/protocolo/fase-1': {
      id: '/_authenticated/protocolo/fase-1'
      path: '/fase-1'
      fullPath: '/protocolo/fase-1'
      preLoaderRoute: typeof AuthenticatedProtocoloFase1RouteImport
      parentRoute: typeof AuthenticatedProtocoloRoute
    }
    '/_authenticated/aulas/$lessonId': {
      id: '/_authenticated/aulas/$lessonId'
      path: '/aulas/$lessonId'
      fullPath: '/aulas/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulasLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp-commands': {
      id: '/api/public/webhooks/whatsapp-commands'
      path: '/api/public/webhooks/whatsapp-commands'
      fullPath: '/api/public/webhooks/whatsapp-commands'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/payt': {
      id: '/api/public/webhooks/payt'
      path: '/api/public/webhooks/payt'
      fullPath: '/api/public/webhooks/payt'
      preLoaderRoute: typeof ApiPublicWebhooksPaytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aulas/modulo/$moduloId': {
      id: '/_authenticated/aulas/modulo/$moduloId'
      path: '/aulas/modulo/$moduloId'
      fullPath: '/aulas/modulo/$moduloId'
      preLoaderRoute: typeof AuthenticatedAulasModuloModuloIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/payt/reprocess': {
      id: '/api/public/webhooks/payt/reprocess'
      path: '/reprocess'
      fullPath: '/api/public/webhooks/payt/reprocess'
      preLoaderRoute: typeof ApiPublicWebhooksPaytReprocessRouteImport
      parentRoute: typeof ApiPublicWebhooksPaytRoute
    }
  }
}

interface AuthenticatedProtocoloRouteChildren {
  AuthenticatedProtocoloFase1Route: typeof AuthenticatedProtocoloFase1Route
  AuthenticatedProtocoloFase2Route: typeof AuthenticatedProtocoloFase2Route
  AuthenticatedProtocoloIndexRoute: typeof AuthenticatedProtocoloIndexRoute
}

const AuthenticatedProtocoloRouteChildren: AuthenticatedProtocoloRouteChildren =
  {
    AuthenticatedProtocoloFase1Route: AuthenticatedProtocoloFase1Route,
    AuthenticatedProtocoloFase2Route: AuthenticatedProtocoloFase2Route,
    AuthenticatedProtocoloIndexRoute: AuthenticatedProtocoloIndexRoute,
  }

const AuthenticatedProtocoloRouteWithChildren =
  AuthenticatedProtocoloRoute._addFileChildren(
    AuthenticatedProtocoloRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedFase2Route: typeof AuthenticatedFase2Route
  AuthenticatedFlacidezRoute: typeof AuthenticatedFlacidezRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPontosRoute: typeof AuthenticatedPontosRoute
  AuthenticatedProtocoloRoute: typeof AuthenticatedProtocoloRouteWithChildren
  AuthenticatedQuizFase1Route: typeof AuthenticatedQuizFase1Route
  AuthenticatedSeuProtocoloRoute: typeof AuthenticatedSeuProtocoloRoute
  AuthenticatedAulasLessonIdRoute: typeof AuthenticatedAulasLessonIdRoute
  AuthenticatedSugestoesChefeTipoRoute: typeof AuthenticatedSugestoesChefeTipoRoute
  AuthenticatedAulasIndexRoute: typeof AuthenticatedAulasIndexRoute
  AuthenticatedAulasModuloModuloIdRoute: typeof AuthenticatedAulasModuloModuloIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedFase2Route: AuthenticatedFase2Route,
  AuthenticatedFlacidezRoute: AuthenticatedFlacidezRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPontosRoute: AuthenticatedPontosRoute,
  AuthenticatedProtocoloRoute: AuthenticatedProtocoloRouteWithChildren,
  AuthenticatedQuizFase1Route: AuthenticatedQuizFase1Route,
  AuthenticatedSeuProtocoloRoute: AuthenticatedSeuProtocoloRoute,
  AuthenticatedAulasLessonIdRoute: AuthenticatedAulasLessonIdRoute,
  AuthenticatedSugestoesChefeTipoRoute: AuthenticatedSugestoesChefeTipoRoute,
  AuthenticatedAulasIndexRoute: AuthenticatedAulasIndexRoute,
  AuthenticatedAulasModuloModuloIdRoute: AuthenticatedAulasModuloModuloIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicWebhooksPaytRouteChildren {
  ApiPublicWebhooksPaytReprocessRoute: typeof ApiPublicWebhooksPaytReprocessRoute
}

const ApiPublicWebhooksPaytRouteChildren: ApiPublicWebhooksPaytRouteChildren = {
  ApiPublicWebhooksPaytReprocessRoute: ApiPublicWebhooksPaytReprocessRoute,
}

const ApiPublicWebhooksPaytRouteWithChildren =
  ApiPublicWebhooksPaytRoute._addFileChildren(
    ApiPublicWebhooksPaytRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicCheckAccessRoute: ApiPublicCheckAccessRoute,
  ApiPublicGrantAccessRoute: ApiPublicGrantAccessRoute,
  ApiPublicWebhooksPaytRoute: ApiPublicWebhooksPaytRouteWithChildren,
  ApiPublicWebhooksWhatsappCommandsRoute:
    ApiPublicWebhooksWhatsappCommandsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
